/*
Created: 11/19/2013
Modified: 10/31/2023
Model: MACEBASE2
Database: Oracle 11g Release 2
*/




-- Drop relationships section -------------------------------------------------

ALTER TABLE clamsbase2.underway_data DROP CONSTRAINT measure_types_uw_data_fk
/
ALTER TABLE clamsbase2.underway_data DROP CONSTRAINT surveys_uw_data
/
ALTER TABLE clamsbase2.LENGTH_HISTOGRAM DROP CONSTRAINT len_hist_subcat_fk
/
ALTER TABLE clamsbase2.protected_spp_event_parameters DROP CONSTRAINT prot_spp_ev_parm_devices_fk
/
ALTER TABLE clamsbase2.LENGTH_HISTOGRAM DROP CONSTRAINT len_hist_gear_parts_fk
/
ALTER TABLE clamsbase2.LENGTH_HISTOGRAM DROP CONSTRAINT len_hist_spp_fk
/
ALTER TABLE clamsbase2.LENGTH_HISTOGRAM DROP CONSTRAINT len_hist_samples_fk
/
ALTER TABLE clamsbase2.CATCH_SUMMARY DROP CONSTRAINT catch_summary_gear_parts_fk
/
ALTER TABLE clamsbase2.CATCH_SUMMARY DROP CONSTRAINT catch_summary_spp_subcat_fk
/
ALTER TABLE clamsbase2.CATCH_SUMMARY DROP CONSTRAINT catch_summary_spp_fk
/
ALTER TABLE clamsbase2.CATCH_SUMMARY DROP CONSTRAINT catch_summary_samples_fk
/
ALTER TABLE clamsbase2.CATCH_SUMMARY DROP CONSTRAINT catch_sum_samples_fk
/
ALTER TABLE clamsbase2.OVERRIDES DROP CONSTRAINT overrides_events_fk
/
ALTER TABLE clamsbase2.protected_spp_event_data DROP CONSTRAINT p_spp_evp_p_spp_ev_data_fk
/
ALTER TABLE clamsbase2.protected_spp_event_parameters DROP CONSTRAINT param_units_p_spp_ev_parms_fk
/
ALTER TABLE clamsbase2.protected_spp_event_parameters DROP CONSTRAINT param_types_p_spp_ev_parms_fk
/
ALTER TABLE clamsbase2.protected_spp_event_data DROP CONSTRAINT p_spp_ev_p_spp_ev_data_fk
/
ALTER TABLE clamsbase2.protected_spp_events DROP CONSTRAINT personnel_p_spp_events_fk
/
ALTER TABLE clamsbase2.protected_spp_events DROP CONSTRAINT surveys_p_spp_events_fk
/
ALTER TABLE clamsbase2.QUALITY_CONTROL DROP CONSTRAINT QC_TYPE_QC_CONT_FK
/
ALTER TABLE clamsbase2.QUALITY_CONTROL DROP CONSTRAINT EVENT_QC_CONT_FK
/
ALTER TABLE clamsbase2.surveys DROP CONSTRAINT ports_survey_start_fk
/
ALTER TABLE clamsbase2.surveys DROP CONSTRAINT ports_survey_end_fk
/
ALTER TABLE clamsbase2.SPECIMEN DROP CONSTRAINT mat_table_specimen_fk
/
ALTER TABLE clamsbase2.surveys DROP CONSTRAINT sea_areas_surveys_fk
/
ALTER TABLE clamsbase2.surveys DROP CONSTRAINT survey_regions_surveys_fk
/
ALTER TABLE clamsbase2.GEAR_ACCESSORY_TYPES DROP CONSTRAINT PARAM_UNITS_GA_TYPES_FK
/
ALTER TABLE clamsbase2.GEAR_ACCESSORY_TYPES DROP CONSTRAINT PARAM_TYPE_GA_TYPES_FK
/
ALTER TABLE clamsbase2.VALIDATION_CONFIGURATION DROP CONSTRAINT V_DEFINITIONS_V_CONFIG_FK
/
ALTER TABLE clamsbase2.surveys DROP CONSTRAINT ships_surveys_fk
/
ALTER TABLE clamsbase2.SPECIES DROP CONSTRAINT species_species_fk
/
ALTER TABLE clamsbase2.PROTOCOL_MAP DROP CONSTRAINT SP_SUBCAT_PROTO_MAP_FK
/
ALTER TABLE clamsbase2.PROTOCOL_MAP DROP CONSTRAINT SPECIES_PROTO_MAP_FK
/
ALTER TABLE clamsbase2.PROTOCOL_MAP DROP CONSTRAINT SPECIMEN_PROTO_PROTO_MAP_FK
/
ALTER TABLE clamsbase2.SAMPLES DROP CONSTRAINT SP_SUBCAT_SAMPLES_FK
/
ALTER TABLE clamsbase2.SPECIES_DATA DROP CONSTRAINT SP_SUBCAT_SP_DATA_FK
/
ALTER TABLE clamsbase2.SPECIES_DATA DROP CONSTRAINT SP_PARAMS_SP_DATA_FK
/
ALTER TABLE clamsbase2.SPECIES_DATA DROP CONSTRAINT SPECIES_SP_DATA_FK
/
ALTER TABLE clamsbase2.SPECIES_ASSOCIATIONS DROP CONSTRAINT SPECIES_SP_ASSOC_FK
/
ALTER TABLE clamsbase2.MEASUREMENT_TYPES DROP CONSTRAINT param_units_measure_types_fk
/
ALTER TABLE clamsbase2.EVENT_PARAMETERS DROP CONSTRAINT param_units_event_params_fk
/
ALTER TABLE clamsbase2.survey_parameters DROP CONSTRAINT param_units_survey_ptypes_fk
/
ALTER TABLE clamsbase2.SAMPLE_PARAMETERS DROP CONSTRAINT param_units_samp_params_fk
/
ALTER TABLE clamsbase2.SPECIES_PARAMETERS DROP CONSTRAINT param_units_sp_params_fk
/
ALTER TABLE clamsbase2.MEASUREMENT_TYPES DROP CONSTRAINT param_types_measure_types_fk
/
ALTER TABLE clamsbase2.SAMPLE_PARAMETERS DROP CONSTRAINT param_types_sample_params_fk
/
ALTER TABLE clamsbase2.SAMPLE_DATA DROP CONSTRAINT samples_sample_data_fk
/
ALTER TABLE clamsbase2.EVENT_PARAMETERS DROP CONSTRAINT param_types_event_params_fk
/
ALTER TABLE clamsbase2.EVENTS DROP CONSTRAINT ships_haul_fk
/
ALTER TABLE clamsbase2.EVENTS DROP CONSTRAINT surveys_haul_fk
/
ALTER TABLE clamsbase2.survey_parameters DROP CONSTRAINT param_types_survey_ptypes_fk
/
ALTER TABLE clamsbase2.surveys DROP CONSTRAINT personnel_surveys_fk
/
ALTER TABLE clamsbase2.survey_data DROP CONSTRAINT survey_survey_parms_fk
/
ALTER TABLE clamsbase2.survey_data DROP CONSTRAINT survey_parm_types_fk
/
ALTER TABLE clamsbase2.SPECIES_ASSOCIATIONS DROP CONSTRAINT SP_SUBCAT_SP_ASSOC_FK
/
ALTER TABLE clamsbase2.SAMPLES DROP CONSTRAINT SAMPLE_SAMPLE_RK
/
ALTER TABLE clamsbase2.SPECIES_PARAMETERS DROP CONSTRAINT SP_PARM_SPP_TYPES_FK
/
ALTER TABLE clamsbase2.SAMPLES DROP CONSTRAINT EVENTS_SAMPLES_FK
/
ALTER TABLE clamsbase2.WORKSTATION_CONFIGURATION DROP CONSTRAINT WRK_CONFIG_WRK_FK
/
ALTER TABLE clamsbase2.VALIDATIONS DROP CONSTRAINT VALIDATIONS_VALDEFS_FK
/
ALTER TABLE clamsbase2.VALIDATIONS DROP CONSTRAINT VALIDATIONS_PROTONAME_FK
/
ALTER TABLE clamsbase2.VALIDATIONS DROP CONSTRAINT VALIDATIONS_MTYPES_FK
/
ALTER TABLE clamsbase2.SPECIMEN DROP CONSTRAINT SPECIMEN_WORKSTATION_FK
/
ALTER TABLE clamsbase2.SPECIMEN DROP CONSTRAINT SPECIMEN_SAMPMETH_FK
/
ALTER TABLE clamsbase2.SPECIMEN DROP CONSTRAINT SPECIMEN_SAMPLE_FK
/
ALTER TABLE clamsbase2.SPECIMEN DROP CONSTRAINT SPECIMEN_PROTONAME_FK
/
ALTER TABLE clamsbase2.SPECIMEN DROP CONSTRAINT SPECIMEN_PERSONNEL_FK
/
ALTER TABLE clamsbase2.SAMPLES DROP CONSTRAINT SAMPLE_SPECIES_FK
/
ALTER TABLE clamsbase2.SAMPLES DROP CONSTRAINT SAMPLE_SAMPLETYPES_FK
/
ALTER TABLE clamsbase2.SAMPLES DROP CONSTRAINT SAMPLE_PERSONNEL_FK
/
ALTER TABLE clamsbase2.SAMPLES DROP CONSTRAINT SAMPLE_GEARPARTS_FK
/
ALTER TABLE clamsbase2.SAMPLE_DATA DROP CONSTRAINT SAMPLE_DATA_SAMPLEPARMS_FK
/
ALTER TABLE clamsbase2.PROTOCOL_DEFINITIONS DROP CONSTRAINT PROTODEF_PROTONAME_FK
/
ALTER TABLE clamsbase2.OVERRIDES DROP CONSTRAINT OVERRIDE_PERSONNEL_FK
/
ALTER TABLE clamsbase2.MEASUREMENT_SETUP DROP CONSTRAINT M_SETUP_WORKSTATION_FK
/
ALTER TABLE clamsbase2.MEASUREMENT_SETUP DROP CONSTRAINT M_SETUP_MTYPES_FK
/
ALTER TABLE clamsbase2.MEASUREMENT_SETUP DROP CONSTRAINT M_SETUP_INPUTDEVICE_FK
/
ALTER TABLE clamsbase2.MEASUREMENT_SETUP DROP CONSTRAINT DEV_INTERFACE_M_SETUP_FK
/
ALTER TABLE clamsbase2.MEASUREMENTS DROP CONSTRAINT MEASUREMENT_SPECIMEN_FK
/
ALTER TABLE clamsbase2.MEASUREMENTS DROP CONSTRAINT MEASUREMENT_MTYPES_FK
/
ALTER TABLE clamsbase2.MEASUREMENTS DROP CONSTRAINT MEASUREMENT_INPUTDEVICE_FK
/
ALTER TABLE clamsbase2.MATURITY_DESCRIPTION DROP CONSTRAINT MATURITY_DESC_MATURITYTABLE_FK
/
ALTER TABLE clamsbase2.EVENTS DROP CONSTRAINT PERSONNEL_EVENTS_FK
/
ALTER TABLE clamsbase2.EVENTS DROP CONSTRAINT EVENT_TYPES_EVENT_FK
/
ALTER TABLE clamsbase2.EVENTS DROP CONSTRAINT EVENT_PERF_EVENTS_FK
/
ALTER TABLE clamsbase2.EVENTS DROP CONSTRAINT GEAR_EVENTS_FK
/
ALTER TABLE clamsbase2.EVENT_DATA DROP CONSTRAINT EVENTS_EVENT_DATA_FK
/
ALTER TABLE clamsbase2.EVENT_DATA DROP CONSTRAINT EVENT_PARMS_EVENT_DATA_FK
/
ALTER TABLE clamsbase2.EVENT_DATA DROP CONSTRAINT GEAR_PARTS_EVENT_DATA_FK
/
ALTER TABLE clamsbase2.EVENT_STREAM_DATA DROP CONSTRAINT MTYPES_EV_STREAM_DATA_FK
/
ALTER TABLE clamsbase2.EVENT_STREAM_DATA DROP CONSTRAINT EVENTS_EV_STREAM_DATA_FK
/
ALTER TABLE clamsbase2.EVENT_STREAM_DATA DROP CONSTRAINT DEVICES_EV_STREAM_DATA_FK
/
ALTER TABLE clamsbase2.GEAR_OPTIONS DROP CONSTRAINT GEAR_OPT_HAULTYPES_FK
/
ALTER TABLE clamsbase2.GEAR_OPTIONS DROP CONSTRAINT GEAR_OPT_HAULPERF_FK
/
ALTER TABLE clamsbase2.GEAR_OPTIONS DROP CONSTRAINT GEAR_OPT_HAULPARMS_FK
/
ALTER TABLE clamsbase2.GEAR_OPTIONS DROP CONSTRAINT GEAR_OPT_GEAR_FK
/
ALTER TABLE clamsbase2.GEAR_OPTIONS DROP CONSTRAINT GEAR_OPT_GEARPARTS_FK
/
ALTER TABLE clamsbase2.GEAR_OPTIONS DROP CONSTRAINT GEAR_OPT_BASKTYPES_FK
/
ALTER TABLE clamsbase2.GEAR_OPTIONS DROP CONSTRAINT GEAR_OPTS_GEARACCTYPS_FK
/
ALTER TABLE clamsbase2.GEAR DROP CONSTRAINT GEAR_GEARTYPES_FK
/
ALTER TABLE clamsbase2.GEAR_ACCESSORY_OPTIONS DROP CONSTRAINT GEAR_ACC_OPTIONS_GEARACCTYP_FK
/
ALTER TABLE clamsbase2.GEAR_ACCESSORY DROP CONSTRAINT GEAR_ACC_EVENTS_FK
/
ALTER TABLE clamsbase2.GEAR_ACCESSORY DROP CONSTRAINT GEAR_ACC_GEARACCTYPES_FK
/
ALTER TABLE clamsbase2.GEAR_PARTITIONS DROP CONSTRAINT GEARPARTS_PARTYPES_FK
/
ALTER TABLE clamsbase2.DEVICE_CONFIGURATION DROP CONSTRAINT DEVCONFIG_DEVPARMS_FK
/
ALTER TABLE clamsbase2.DEVICE_CONFIGURATION DROP CONSTRAINT DEVCONFIG_DEVICE_FK
/
ALTER TABLE clamsbase2.CONDITIONALS DROP CONSTRAINT CONDITIONALS_PROTONAME_FK
/
ALTER TABLE clamsbase2.CONDITIONALS DROP CONSTRAINT CONDITIONALS_CONDEFS_FK
/
ALTER TABLE clamsbase2.BASKETS DROP CONSTRAINT BASKET_SAMPLE_FK
/
ALTER TABLE clamsbase2.BASKETS DROP CONSTRAINT BASKET_INPUTDEVICE_FK
/
ALTER TABLE clamsbase2.BASKETS DROP CONSTRAINT BASKET_BASKTYPES_FK
/


-- Drop triggers for tables section -------------------------------------------------

DROP TRIGGER clamsbase2.SPECIMEN_BEF_UPD_ROW
/
DROP TRIGGER clamsbase2.SPECIMEN_BEF_INS_ROW
/
DROP TRIGGER clamsbase2.SAMPLE_BEF_UPD_ROW
/
DROP TRIGGER clamsbase2.SAMPLE_BEF_INS_ROW
/
DROP TRIGGER clamsbase2.OVERRIDES_BEF_INS_UPD_ROW
/
DROP TRIGGER clamsbase2.MEASUREMENTS_BEF_UPD_ROW
/
DROP TRIGGER clamsbase2.BASKET_BEF_UPD_ROW
/
DROP TRIGGER clamsbase2.BASKET_BEF_INS_ROW
/


-- Drop keys for tables section -------------------------------------------------

ALTER TABLE clamsbase2.underway_data DROP CONSTRAINT PK_underway_data
/
ALTER TABLE clamsbase2.protected_spp_species DROP CONSTRAINT protected_spp_species_pk
/
ALTER TABLE clamsbase2.LENGTH_HISTOGRAM DROP CONSTRAINT PK_LENGTH_HISTOGRAM
/
ALTER TABLE clamsbase2.CATCH_SUMMARY DROP CONSTRAINT PK_CATCH_SUMMARY
/
ALTER TABLE clamsbase2.protected_spp_event_parameters DROP CONSTRAINT prot_spp_event_parm_pk
/
ALTER TABLE clamsbase2.protected_spp_event_data DROP CONSTRAINT prot_spp_event_data_pk
/
ALTER TABLE clamsbase2.protected_spp_events DROP CONSTRAINT prot_spp_events_pk
/
ALTER TABLE clamsbase2.EXTENDED_SAMPLE_COLLECTIONS DROP CONSTRAINT EX_SAMPLE_COL_PK
/
ALTER TABLE clamsbase2.QUALITY_CONTROL DROP CONSTRAINT Key24
/
ALTER TABLE clamsbase2.QC_TYPES DROP CONSTRAINT QC_TYPES_PK
/
ALTER TABLE clamsbase2.survey_ports DROP CONSTRAINT survey_ports_pk
/
ALTER TABLE clamsbase2.survey_sea_areas DROP CONSTRAINT SURVEY_SEA_AREAS_PK
/
ALTER TABLE clamsbase2.APPLICATION_EVENTS DROP CONSTRAINT APPLICATION_EVENTS_PK
/
ALTER TABLE clamsbase2.survey_regions DROP CONSTRAINT survey_regions_pk
/
ALTER TABLE clamsbase2.SPECIES_DATA DROP CONSTRAINT SP_DATA_PK
/
ALTER TABLE clamsbase2.PARAMETER_UNITS DROP CONSTRAINT param_units_pk
/
ALTER TABLE clamsbase2.survey_data DROP CONSTRAINT survey_parms_pk
/
ALTER TABLE clamsbase2.surveys DROP CONSTRAINT survey_pk
/
ALTER TABLE clamsbase2.survey_parameters DROP CONSTRAINT survey_parms_type_pk
/
ALTER TABLE clamsbase2.SHIPS DROP CONSTRAINT ship_pk
/
ALTER TABLE clamsbase2.SPECIES_ASSOCIATIONS DROP CONSTRAINT SP_ASSOC_PK
/
ALTER TABLE clamsbase2.SPECIES_SUBCATEGORIES DROP CONSTRAINT species_subcategory_PK
/
ALTER TABLE clamsbase2.PARAMETER_TYPES DROP CONSTRAINT parameter_types_pk
/
ALTER TABLE clamsbase2.SPECIES_PARAMETERS DROP CONSTRAINT species_parameters_pk
/
ALTER TABLE clamsbase2.WORKSTATION_CONFIGURATION DROP CONSTRAINT WRK_CONFIG_PK
/
ALTER TABLE clamsbase2.WORKSTATIONS DROP CONSTRAINT WORKSTATION_PK
/
ALTER TABLE clamsbase2.VALIDATION_DEFINITIONS DROP CONSTRAINT VALIDATION_DEF_PK
/
ALTER TABLE clamsbase2.VALIDATION_CONFIGURATION DROP CONSTRAINT VAL_CONFIG_PK
/
ALTER TABLE clamsbase2.VALIDATIONS DROP CONSTRAINT VALIDATIONS_PK
/
ALTER TABLE clamsbase2.SPECIMEN_PROTOCOL DROP CONSTRAINT SPEC_PROTOCOL_PK
/
ALTER TABLE clamsbase2.SPECIMEN DROP CONSTRAINT SPECIMEN_PK
/
ALTER TABLE clamsbase2.SPECIES DROP CONSTRAINT SPECIES_PK
/
ALTER TABLE clamsbase2.SAMPLING_METHODS DROP CONSTRAINT SAMPLE_METHODS_PK
/
ALTER TABLE clamsbase2.SAMPLE_TYPES DROP CONSTRAINT SAMPLE_TYPES_PK
/
ALTER TABLE clamsbase2.SAMPLE_PARAMETERS DROP CONSTRAINT SAMPLE_PARMS_PK
/
ALTER TABLE clamsbase2.SAMPLE_DATA DROP CONSTRAINT SAMPLE_DATA_PK
/
ALTER TABLE clamsbase2.SAMPLES DROP CONSTRAINT SAMPLE_PK
/
ALTER TABLE clamsbase2.PROTOCOL_MAP DROP CONSTRAINT PROTO_MAP_PK
/
ALTER TABLE clamsbase2.PERSONNEL DROP CONSTRAINT PERSONNEL_PK
/
ALTER TABLE clamsbase2.OVERRIDES DROP CONSTRAINT OVERRIDE_PK
/
ALTER TABLE clamsbase2.MEASUREMENT_TYPES DROP CONSTRAINT MEASUREMENT_TYPES_PK
/
ALTER TABLE clamsbase2.MEASUREMENT_SETUP DROP CONSTRAINT M_SETUP_PK
/
ALTER TABLE clamsbase2.MEASUREMENTS DROP CONSTRAINT MEASUREMENT_PK
/
ALTER TABLE clamsbase2.MATURITY_TABLES DROP CONSTRAINT MATURITY_TABLES_PK
/
ALTER TABLE clamsbase2.MATURITY_DESCRIPTION DROP CONSTRAINT MATURITY_DESC_PK
/
ALTER TABLE clamsbase2.HAUL_WEIGHT_TYPES DROP CONSTRAINT HAUL_WT_TYPE_PK
/
ALTER TABLE clamsbase2.EVENT_TYPES DROP CONSTRAINT HAUL_TYPES_PK
/
ALTER TABLE clamsbase2.EVENT_STREAM_DATA DROP CONSTRAINT EVENT_STR_DATA_PK
/
ALTER TABLE clamsbase2.EVENT_PERFORMANCE DROP CONSTRAINT HAUL_PERF_PK
/
ALTER TABLE clamsbase2.EVENT_PARAMETERS DROP CONSTRAINT HAUL_PARMS_PK
/
ALTER TABLE clamsbase2.EVENT_DATA DROP CONSTRAINT EVENT_DATA_PK
/
ALTER TABLE clamsbase2.EVENTS DROP CONSTRAINT EVENTS_PK
/
ALTER TABLE clamsbase2.GEAR_TYPES DROP CONSTRAINT GEAR_TYPES_PK
/
ALTER TABLE clamsbase2.GEAR_PARTITION_TYPES DROP CONSTRAINT GEAR_PAR_TYPES_PK
/
ALTER TABLE clamsbase2.GEAR_PARTITIONS DROP CONSTRAINT GEAR_PARTS_PK
/
ALTER TABLE clamsbase2.GEAR_ACCESSORY_TYPES DROP CONSTRAINT GEAR_ACC_TYPES_PK
/
ALTER TABLE clamsbase2.GEAR_ACCESSORY_OPTIONS DROP CONSTRAINT GEAR_ACC_OPTIONS_PK
/
ALTER TABLE clamsbase2.GEAR_ACCESSORY DROP CONSTRAINT GEAR_ACC_PK
/
ALTER TABLE clamsbase2.GEAR DROP CONSTRAINT GEAR_PK
/
ALTER TABLE clamsbase2.GEAR DROP CONSTRAINT GEAR_CODE_UNQ
/
ALTER TABLE clamsbase2.DEVICE_PARAMETERS DROP CONSTRAINT DEVICE_PARAMETERS_PK
/
ALTER TABLE clamsbase2.DEVICE_INTERFACES DROP CONSTRAINT DEVINTERFACES_PK
/
ALTER TABLE clamsbase2.DEVICE_CONFIGURATION DROP CONSTRAINT DEVCONFIG_PK
/
ALTER TABLE clamsbase2.DEVICES DROP CONSTRAINT DEVICE_PK
/
ALTER TABLE clamsbase2.DEVICES DROP CONSTRAINT DEVICE_UNQ
/
ALTER TABLE clamsbase2.CONDITIONAL_DEFINITIONS DROP CONSTRAINT CONDITIONAL_DEF_PK
/
ALTER TABLE clamsbase2.CONDITIONALS DROP CONSTRAINT CONDITIONALS_PK
/
ALTER TABLE clamsbase2.BASKET_TYPES DROP CONSTRAINT BASKET_TYPES_PK
/
ALTER TABLE clamsbase2.BASKETS DROP CONSTRAINT BASKET_PK
/
ALTER TABLE clamsbase2.APPLICATION_CONFIGURATION DROP CONSTRAINT APP_CONFIG_PK
/


-- Drop indexes section -------------------------------------------------

DROP INDEX IX_len_hist_spp_fk
/
DROP INDEX IX_catch_summary_spp_fk
/
DROP INDEX EVENT_STR_DATA_TIME_IDX
/


-- Drop tables section ---------------------------------------------------

DROP TABLE clamsbase2.underway_data
/
DROP TABLE clamsbase2.protected_spp_species
/
DROP TABLE clamsbase2.LENGTH_HISTOGRAM
/
DROP TABLE clamsbase2.CATCH_SUMMARY
/
DROP TABLE clamsbase2.protected_spp_event_parameters
/
DROP TABLE clamsbase2.protected_spp_event_data
/
DROP TABLE clamsbase2.protected_spp_events
/
DROP TABLE clamsbase2.EXTENDED_SAMPLE_COLLECTIONS
/
DROP TABLE clamsbase2.QUALITY_CONTROL
/
DROP TABLE clamsbase2.QC_TYPES
/
DROP TABLE clamsbase2.survey_ports
/
DROP TABLE clamsbase2.survey_sea_areas
/
DROP TABLE clamsbase2.APPLICATION_EVENTS
/
DROP TABLE clamsbase2.survey_regions
/
DROP TABLE clamsbase2.SPECIES_DATA
/
DROP TABLE clamsbase2.PARAMETER_UNITS
/
DROP TABLE clamsbase2.SPECIES_ASSOCIATIONS
/
DROP TABLE clamsbase2.SPECIES_SUBCATEGORIES
/
DROP TABLE clamsbase2.PARAMETER_TYPES
/
DROP TABLE clamsbase2.SPECIES_PARAMETERS
/
DROP TABLE clamsbase2.WORKSTATION_CONFIGURATION
/
DROP TABLE clamsbase2.WORKSTATIONS
/
DROP TABLE clamsbase2.VALIDATION_DEFINITIONS
/
DROP TABLE clamsbase2.VALIDATION_CONFIGURATION
/
DROP TABLE clamsbase2.VALIDATIONS
/
DROP TABLE clamsbase2.SPECIMEN_PROTOCOL
/
DROP TABLE clamsbase2.SPECIMEN
/
DROP TABLE clamsbase2.SPECIES
/
DROP TABLE clamsbase2.SAMPLING_METHODS
/
DROP TABLE clamsbase2.SAMPLE_TYPES
/
DROP TABLE clamsbase2.SAMPLE_PARAMETERS
/
DROP TABLE clamsbase2.SAMPLE_DATA
/
DROP TABLE clamsbase2.SAMPLES
/
DROP TABLE clamsbase2.PROTOCOL_MAP
/
DROP TABLE clamsbase2.PROTOCOL_DEFINITIONS
/
DROP TABLE clamsbase2.PERSONNEL
/
DROP TABLE clamsbase2.OVERRIDES
/
DROP TABLE clamsbase2.MEASUREMENT_TYPES
/
DROP TABLE clamsbase2.MEASUREMENT_SETUP
/
DROP TABLE clamsbase2.MEASUREMENTS
/
DROP TABLE clamsbase2.MATURITY_TABLES
/
DROP TABLE clamsbase2.MATURITY_DESCRIPTION
/
DROP TABLE clamsbase2.HAUL_WEIGHT_TYPES
/
DROP TABLE clamsbase2.EVENT_TYPES
/
DROP TABLE clamsbase2.EVENT_STREAM_DATA
/
DROP TABLE clamsbase2.EVENT_PERFORMANCE
/
DROP TABLE clamsbase2.EVENT_PARAMETERS
/
DROP TABLE clamsbase2.EVENT_DATA
/
DROP TABLE clamsbase2.EVENTS
/
DROP TABLE clamsbase2.GEAR_TYPES
/
DROP TABLE clamsbase2.GEAR_PARTITION_TYPES
/
DROP TABLE clamsbase2.GEAR_PARTITIONS
/
DROP TABLE clamsbase2.GEAR_OPTIONS
/
DROP TABLE clamsbase2.GEAR_ACCESSORY_TYPES
/
DROP TABLE clamsbase2.GEAR_ACCESSORY_OPTIONS
/
DROP TABLE clamsbase2.GEAR_ACCESSORY
/
DROP TABLE clamsbase2.GEAR
/
DROP TABLE clamsbase2.DEVICE_PARAMETERS
/
DROP TABLE clamsbase2.DEVICE_INTERFACES
/
DROP TABLE clamsbase2.DEVICE_CONFIGURATION
/
DROP TABLE clamsbase2.DEVICES
/
DROP TABLE clamsbase2.CONDITIONAL_DEFINITIONS
/
DROP TABLE clamsbase2.CONDITIONALS
/
DROP TABLE clamsbase2.BASKET_TYPES
/
DROP TABLE clamsbase2.BASKETS
/
DROP TABLE clamsbase2.APPLICATION_CONFIGURATION
/
DROP TABLE clamsbase2.survey_parameters
/
DROP TABLE clamsbase2.survey_data
/
DROP TABLE clamsbase2.surveys
/
DROP TABLE clamsbase2.SHIPS
/

-- Drop sequences section --------------------------------------------------- 

DROP SEQUENCE clamsbase2.PROT_SPP_ID_SEQ
/
DROP SEQUENCE clamsbase2.SPECIMEN_ID_SEQ
/
DROP SEQUENCE clamsbase2.SAMPLE_ID_SEQ
/
DROP SEQUENCE clamsbase2.BASKET_ID_SEQ
/

-- Grant permissions section -------------------------------------------------




